version: "3"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: my-rds-instance.c**********.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: yash
      WORDPRESS_DB_PASSWORD: yash123$$
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
